name: test

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Run Stuff
      run: |
        brew install oras
        oras version
        echo ${{ github.token }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        oras push ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:latest ./src/hello.txt:application/vnd.unknown.layer.v1+txt
    - name: Delete Untagged Images
      uses: actions/github-script@v3
      env:
        OWNER: ${{ github.repository_owner }}
        PACKAGE_NAME: ${{ github.event.repository.name }}
        PER_PAGE: 100
      with:
        github-token: ${{ github.token }}
        script: |
          const response = await github.request("GET /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
            { per_page: ${{ env.PER_PAGE }}
          });
          for(version of response.data) {
              if (version.metadata.container.tags.length == 0) {
                  console.log("delete " + version.id)
                  const deleteResponse = await github.request("DELETE /${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                  console.log("status " + deleteResponse.status)
              }
          }