name: test

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Run Stuff
      run: |
        brew install oras
        oras version
        echo ${{ github.token }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        oras push ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}:latest ./src/hello.txt:application/vnd.unknown.layer.v1+txt