name: test

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Run Stuff
      run: |
        brew install oras
        oras version
        echo ${{ github.token }} | oras login ghcr.io -u ${{ github.actor }} --password-stdin
        oras push ghcr.io/${{ github.repository }}/oras-test:latest ./src/hello.txt:application/vnd.unknown.layer.v1+txt
##        oras push ghcr.io/${{ github.repository }}/oras-test:latest --manifest-config /dev/null:application/vnd.homebrew.brew.config ./brew-file.tar.gz:application/tar+gzip
    - uses: actions/delete-package-versions@v3
      with:
        package-name: 'oras-test'
        min-versions-to-keep: 3