name: test

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: stuff
      run: |
        brew install oras
        oras version
        echo $GITHUB_TOKEN | oras login ghcr.io -u foobar --password-stdin